### PR TITLE
Support installation with Python 3

### PR DESCRIPTION
**Pull request by sallner**
The documentation of Fanstatic depends on this package and the build is currently broken with Python 3. This PR should fix the issue with the installation. This would also close 3 issues on bitbucket.

### CODE REVIEW

**Comment by sallner** [comment]
@birkenfeld What do you think of this PR. Can I do anything to help with a merge?

**Comment by sallner** [comment]
@birkenfeld could please consider this PR and a release?

**Comment by icemac** [comment]
@birkenfeld What has to be done to get this PR merged?

**Comment by icemac** [comment]
CC: @dhellmann

**Comment by dhellmann** [comment]
I've contacted @birkenfeld via email. Let's give him some time to reply.

**Comment by birkenfeld** [comment]
Sorry for the long silence.  I'm happy with any of you taking over maintenance here; for now I'll add @dhellmann as maintainer on the PyPI project.

**Comment by dhellmann** [comment]
Thanks, @birkenfeld!

@icemac & @sallner, I can add both of you as maintainers of the repo if you're interested. Let me know.

**Comment by sallner** [comment]
@dhellmann It is okay, if you only add me as maintainer for now. PyPI is the same username as here.

**Comment by dhellmann** [comment]
@sallner I have invited you to be a member of the org and admin of this repository. I also invited you to be an owner of the PyPI project.

@icemac I have invited you to be a member of the Github org.

**Comment by sallner** [comment]
@dhellmann Thank you for the invitations. I will proceed further with this PR and the repository.

**Pull request merged**
